# -*- coding: utf-8 -*-
"""
Created on Wed May  8 11:11:45 2024

@author: DNACONSULT
"""

import query
import pandas as pd
import numpy as np
import os
import datetime



# search_alleles = ['A']
# chromossome_num = 1
# position = 98352053

# snps = query.dbsnp37(search_alleles,chromossome_num, position)


files_23andme = os.listdir('../Data/dbsnp_api/23andme')

file_name = '../Data/dbsnp_api/23andme/'+files_23andme[1]

for k in range(0,1):#len(files_23andme)):
    
    
    file_name = '../Data/dbsnp_api/23andme/'+files_23andme[k]
    print('Preenchendo arquivo',file_name)
    
    
    source_file = pd.read_csv(file_name, comment='#', header = None, delimiter = '\t')
    source_file = np.array(source_file)
    
    
    probable_rsNum_list = ['.']*len(source_file)
    
    date_str = datetime.datetime.now().strftime("%c")
    log_total='#busca no arquivo %s feita em '%(files_23andme[k])+date_str+'\n'
    
    not_found_count = 0
    for l in range(0,20):#len(source_file)):
        print('#busca no arquivo %s '%(files_23andme[k]))
        print('buscando linha %d de %d'%(l,len(source_file)))
        log_total+='buscando linha %d de %d do'%(l,len(source_file))+'\n'
        print()
        log_total+='\n'
    
        no_rsid, chromossome_line, position_line, genotype_line = source_file[l]
        
        print('busca: chr%s : %d '%(chromossome_line,position_line)+genotype_line)
        log_total+='busca: chr%s : %d '%(chromossome_line,position_line)+genotype_line+'\n'
        

        search_alleles_query = [genotype_line[0]]
        if genotype_line[0] != genotype_line[1]:
            search_alleles_query.append(genotype_line[1])
        
        chromossome_num_query = chromossome_line
        position_query = int(position_line)
        
        snps, position_result,log_i = query.dbsnp37(search_alleles_query,
                                                    chromossome_num_query,
                                                    position_query,
                                                    return_log=True,
                                                    query_folder = '../Out/dbsnp_api/queries/')#, do_print=False)

        log_total+=log_i
        probable_rsNum = '.'
        for i in range(len(position_result)):
            pos = int(position_result[i])
            if abs(pos-position_query)<3:
                probable_rsNum = snps[i]
                
        if probable_rsNum=='.':
            not_found_count+=1
        
        print()
        log_total+='\n'
    
        print('encontrado')        
        log_total+='encontrado'+'\n'
    
        print(probable_rsNum)
        log_total+=probable_rsNum+'\n'
        
        print('##########################')
        log_total+='##########################'+'\n'
        
        probable_rsNum_list[l] = probable_rsNum
    
    print('nao foram encontrados %d o que significa %.2f%% das linhas'%(not_found_count,100*(not_found_count/len(source_file))))
    
    log_total+='nao foram encontrados %d o que significa %.2f%% das linhas'%(not_found_count,100*(not_found_count/len(source_file)))
    # print(log_total)
    file_log = open('../Out/dbsnp_api/log/'+files_23andme[k][:-4]+'.log', 'w')
    file_log.write(log_total)
    file_log.close()
    
    heading = "# This data file generated by PLINK, but processed with the dbSNP API at: Tue Apr 30 19:59:40 2024"
    heading+="#"
    heading+="# Below is a text version of your data.  Fields are TAB-separated."
    heading+="# Each line corresponds to a single SNP.  For each SNP, we provide its"
    heading+="# identifier, its location on a reference human genome, and the genotype call."
    heading+="# For further information (e.g. which reference build was used), consult the"
    heading+="# original source of your data."
    heading+="#"
    # heading+="# rsid	chromosome	position	genotype"
    
    out_file = pd.DataFrame(source_file, columns = ["# rsid","chromosome", "position", "genotype"])
    out_file['# rsid'] = probable_rsNum_list
    out_file.set_index(['# rsid'], inplace=True)
    
    out_file.to_csv('../Out/dbsnp_api/23andme_complete/'+files_23andme[k], sep='\t')
    
    print()
    print()
    print()



